# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  RED: '\033[0;31m'
  GREEN: '\033[0;32m'
  PPL: '\033[0;35m'
  NC: '\033[0m'

tasks:
  default:
    desc: Terraform apply
    cmds:
      - echo -e "{{ .PPL }}task --list to see all the tasks !{{ .NC }}"
    silent: true
  fmt:
    desc: Terraform fmt
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform fmt...{{ .NC }}"
        cd terraform && terraform fmt
    silent: true
  init:
    desc: Terraform init
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform init...{{ .NC }}"
        cd terraform && terraform init
    silent: true
  plan:
    desc: Terraform plan
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform plan...{{ .NC }}"
        cd terraform && terraform plan
    silent: true
  apply:
    desc: Terraform apply
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform apply...{{ .NC }}"
        cd terraform && terraform apply
    silent: true
  output:
    desc: Terraform output
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform output...{{ .NC }}"
        cd terraform && terraform output
    silent: true
  down:
    desc: Terraform destroy
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform destroy...{{ .NC }}"
        cd terraform && terraform destroy
      - |
        echo -e "{{ .PPL }}Rm inventory...{{ .NC }}"
        rm -f ansible/inventory/inventory.ini
    silent: true
  show:
    desc: Terraform show
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform show...{{ .NC }}"
        cd terraform && terraform show
    silent: true
  tfvars:
    desc: Create a terraform.tfvars
    cmds:
      - bash scripts/tfvars.sh
    silent: true
