---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  RED: "\\033[0;31m"
  GREEN: "\\033[0;32m"
  PPL: "\\033[0;35m"
  NC: "\\033[0m"
  VOLUME: ""
  PROFILE: ""
  DOCKER_USER: kazibuya

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list
    silent: true

# ──────────────────────────────────────────
# SETUP
# ──────────────────────────────────────────
  keygen:
    desc: Create melange key for build image
    cmds:
      - |
        echo -e "{{ .PPL }}Melange key generation...{{ .NC }}"
        cd melange && melange keygen
    silent: true

  pipeline:
    desc: Fetch pipeline repo of WolfiOS
    cmds:
      - |
        git clone --depth 1 --filter=blob:none --sparse https://github.com/wolfi-dev/os.git /tmp/wolfi-os &&
        cd /tmp/wolfi-os && git sparse-checkout set pipelines && git checkout &&
        cp -r pipelines {{.ROOT_DIR}}/melange/
        rm -rf /tmp/wolfi-os

# ──────────────────────────────────────────
# TERRAFORM
# ──────────────────────────────────────────
  terraform:fmt:
    desc: Terraform fmt
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform fmt...{{ .NC }}"
        cd terraform && terraform fmt
    silent: true
  terraform:init:
    desc: Terraform init
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform init...{{ .NC }}"
        cd terraform && terraform init
    silent: true
  terraform:plan:
    desc: Terraform plan
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform plan...{{ .NC }}"
        cd terraform && terraform plan
    silent: true
  terraform:apply:
    desc: Terraform apply
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform apply...{{ .NC }}"
        cd terraform && terraform apply
    silent: true
  terraform:output:
    desc: Terraform output
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform output...{{ .NC }}"
        cd terraform && terraform output
    silent: true
  terraform:down:
    desc: Terraform destroy
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform destroy...{{ .NC }}"
        cd terraform && terraform destroy
      - |
        echo -e "{{ .PPL }}Rm inventory...{{ .NC }}"
        rm -f ansible/inventory/inventory.ini
    silent: true
  terraform:show:
    desc: Terraform show
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform show...{{ .NC }}"
        cd terraform && terraform show
    silent: true
  terraform:tfvars:
    desc: Create a terraform.tfvars
    cmds:
      - bash scripts/tfvars.sh
    silent: true
  # ──────────────────────────────────────────
  # ANSIBLE
  # ──────────────────────────────────────────
  ansible:help:
    desc: Ansible tasks
    cmds:
      - |
        echo -e "{{ .PPL }}Ansible tasks{{ .NC }}"
        echo -e "{{ .PPL }Run: task ansible:test{{ .NC }}"


  ansible:lint:
    desc: Ansible lint
    cmds:
      - ansible-lint .
    silent: true

  ansible:test:
    desc: "Ansible Molecule Tests for a specific roles or all of them. Usage: task ansible:test [role=wordpress]"
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - |
        if [ -n "{{ .role }}" ]; then
          if [ -d "ansible/roles/{{ .role }}/molecule/default" ]; then
            echo -e "{{ .PPL }}Running Molecule test for role: {{ .role }}{{ .NC }}"
            cd ansible/roles/{{.role}} && molecule destroy && molecule test
          else
            echo -e "{{ .PPL }}Role {{ .role }} not found{{ .NC }}"
            exit 1
          fi
        else
          echo -e "{{ .PPL }}Running tests for all roles{{ .NC }}"
          for role_dir in ansible/roles/*; do
            echo -e "{{.role_dir}}"
            if [ -d "$role_dir/molecule/default" ]; then
              echo -e "{{.PPL}}Testing role: $(basename $role_dir){{.NC}}"
              (cd "$role_dir" && molecule destroy && molecule test)
            fi
          done
        fi
    silent: true

  ansible:play:
    desc: "Launch Ansible site playbook"
    dir: "{{.TASKFILE_DIR}}/ansible"
    cmds:
      - ANSIBLE_CONFIG=../ansible.cfg ansible-playbook -i inventory/inventory.ini site.yml --vault-id cloudone@{{.TASKFILE_DIR}}/.vault_pass_cloudone
        --diff

  ansible:wordpress:
    desc: "Run ONLY the wordpress role tasks"
    dir: "{{.TASKFILE_DIR}}/ansible"
    cmds:
      - ansible-playbook -i inventory/inventory.ini site.yml --vault-id cloudone@{{.TASKFILE_DIR}}/.vault_pass_cloudone
        --tags wordpress --diff

  ansible:boot:
    desc: "Run ONLY the wordpress role tasks"
    dir: "{{.TASKFILE_DIR}}/ansible"
    cmds:
      - ansible-playbook -i inventory/inventory.ini site.yml --vault-id cloudone@{{.TASKFILE_DIR}}/.vault_pass_cloudone
        --tags bootstrap --diff

  ansible:docker:
    desc: "Run ONLY the wordpress role tasks"
    dir: "{{.TASKFILE_DIR}}/ansible"
    cmds:
      - ansible-playbook -i inventory/inventory.ini site.yml --vault-id cloudone@{{.TASKFILE_DIR}}/.vault_pass_cloudone
        --tags docker --diff

  # ──────────────────────────────────────────
  # DOCKER COMPOSE
  # ──────────────────────────────────────────
  compose:help:
    desc: Some exemples
    cmds:
      - |
        echo -e "{{ .PPL }}WORKFLOW EXEMPLE{{ .NC }}"
        echo -e "{{ .PPL }}Run: task compose:up PROFILE=monitoring for grafana and prometheus{{ .NC }}"
        echo -e "{{ .PPL }}Run: task compose:down PROFILE=monitoring VOLUME=true to add -v{{ .NC }}"
    silent: true
  compose:up:
    desc: Up the docker compose in local
    cmds:
      - |
        echo -e "{{ .PPL }}Process compose up...{{ .NC }}"
        cd compose && docker compose {{if .PROFILE}}--profile {{.PROFILE}}{{end}} up -d
    silent: true
  compose:down:
    desc: down the docker compose in local
    cmds:
      - |
        echo -e "{{ .PPL }}Process compose down...{{ .NC }}"
        cd compose && docker compose {{if .PROFILE}}--profile {{.PROFILE}}{{end}} down {{if .VOLUME}}-v{{end}}
    silent: true

# ──────────────────────────────────────────
# CI
# ──────────────────────────────────────────

  act:
    desc: run CI script locally (checkov fail)
    cmds:
      - |
        act --platform ubuntu-latest=catthehacker/ubuntu:act-latest --secret-file .secrets

  checkov:
    desc: run checkov
    cmds:
      - >-
        checkov -d . --output cli
        --quiet
        --output junitxml
        --output-file-path console,results_junitxml.xml
        --soft-fail

# ──────────────────────────────────────────
# MELANGE
# ──────────────────────────────────────────

  melange:
    internal: true
    dir: melange/{{.SERVICE}}
    vars:
      SERVICE: '{{.SERVICE}}'
    cmds:
      - rm -rf packages
      - melange build {{.SERVICE}}.yaml --arch amd64 --signing-key ../melange.rsa --pipeline-dir ../pipelines

  melange:angie:
    cmds:
      - task: melange
        vars: { SERVICE: angie }

  melange:healthcheck-http:
    cmds:
      - task: melange
        vars: { SERVICE: healthcheck-http }

  melange:healthcheck-sql:
    cmds:
      - task: melange
        vars: { SERVICE: healthcheck-sql }

  melange:phpmyadmin:
    cmds:
      - task: melange
        vars: { SERVICE: phpmyadmin }

  melange:mariadb:
    cmds:
      - task: melange
        vars: { SERVICE: mariadb }

  melange:wordpress:
    cmds:
      - task: melange
        vars: { SERVICE: wordpress }

# ──────────────────────────────────────────
# APKO
# ──────────────────────────────────────────

  apko:
    internal: true
    dir: melange/{{.SERVICE}}
    vars:
      TAG: '{{.TAG | default "latest"}}'
    cmds:
      - apko build apko.yaml {{.DOCKER_USER}}/{{.SERVICE}}:{{.TAG}} {{.SERVICE}}.tar
      - docker load < {{.SERVICE}}.tar

  apko:angie:
    cmds:
      - task: apko
        vars: { SERVICE: angie }

  apko:phpmyadmin:
    cmds:
      - task: apko
        vars: { SERVICE: phpmyadmin }

  apko:mariadb:
    cmds:
      - task: apko
        vars: { SERVICE: mariadb }

  apko:wordpress:
    cmds:
      - task: apko
        vars: { SERVICE: wordpress }
