# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  RED: '\033[0;31m'
  GREEN: '\033[0;32m'
  PPL: '\033[0;35m'
  NC: '\033[0m'
  VOLUME: ""
  PROFILE: ""

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list
    silent: true
# ──────────────────────────────────────────
# TERRAFORM
# ──────────────────────────────────────────
  fmt:
    desc: Terraform fmt
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform fmt...{{ .NC }}"
        cd terraform && terraform fmt
    silent: true
  init:
    desc: Terraform init
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform init...{{ .NC }}"
        cd terraform && terraform init
    silent: true
  plan:
    desc: Terraform plan
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform plan...{{ .NC }}"
        cd terraform && terraform plan
    silent: true
  apply:
    desc: Terraform apply
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform apply...{{ .NC }}"
        cd terraform && terraform apply
    silent: true
  output:
    desc: Terraform output
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform output...{{ .NC }}"
        cd terraform && terraform output
    silent: true
  down:
    desc: Terraform destroy
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform destroy...{{ .NC }}"
        cd terraform && terraform destroy
      - |
        echo -e "{{ .PPL }}Rm inventory...{{ .NC }}"
        rm -f ansible/inventory/inventory.ini
    silent: true
  show:
    desc: Terraform show
    cmds:
      - |
        echo -e "{{ .PPL }}Process terraform show...{{ .NC }}"
        cd terraform && terraform show
    silent: true
  tfvars:
    desc: Create a terraform.tfvars
    cmds:
      - bash scripts/tfvars.sh
    silent: true
# ──────────────────────────────────────────
# DOCKER COMPOSE
# ──────────────────────────────────────────
  compose:help:
    desc: Some exemples
    cmds: 
      - |
        echo -e "{{ .PPL }}WORKFLOW EXEMPLE{{ .NC }}"
        echo -e "{{ .PPL }}Run: task compose:up PROFILE=monitoring for grafana and prometheus{{ .NC }}"
        echo -e "{{ .PPL }}Run: task compose:down PROFILE=monitoring VOLUME=true to add -v{{ .NC }}"
    silent: true
  compose:up:
    desc: Up the docker compose in local
    cmds: 
      - |
        echo -e "{{ .PPL }}Process compose up...{{ .NC }}"
        cd compose && docker compose {{if .PROFILE}}--profile {{.PROFILE}}{{end}} up -d
    silent: true
  compose:down:
    desc: down the docker compose in local
    cmds:
      - |
        echo -e "{{ .PPL }}Process compose down...{{ .NC }}"
        cd compose && docker compose {{if .PROFILE}}--profile {{.PROFILE}}{{end}} down {{if .VOLUME}}-v{{end}}
    silent: true
