---
wordpress_project_name: "cloudone"

wordpress_db_port: 3306
wordpress_db_innodb_buffer_pool_size: "128M"
wordpress_db_user: "mysql"
wordpress_db_group: "mysql"
wordpress_db_mem_limit: "512m"
wordpress_db_mem_res_limit: "256m"
wordpress_db_validate_cmd: >
  "docker run --rm -v \
  dev_db_pass_fallback') }}"
wordpress_wp_password: "{{ global_wp_password | default('dev_wp_pass_fallback') }}"
