---
# wordpress - defaults/main.yml
wordpress_project_name: cloudone
wordpress_subdomain: "{{ global_duckdns_domain | default('nuage-un') }}"
wordpress_domain_name: "{{ wordpress_subdomain if '.' in wordpress_subdomain else wordpress_subdomain + '.duckdns.org' }}"
wordpress_project_path: "{{ global_project_path | default('/opt/cloud-1') }}"

# admins
wordpress_admin_users_list: '{{ global_admin_users_list | default([]) | list }}'

# Pivot variable for tests
wordpress_compose_src: '{{ wordpress_project_path }}'
wordpress_docker_cmd: docker

# Angie ports
wordpress_expose_http: '80'
wordpress_expose_https: '443'

# Host and Container paths
wordpress_db_conf_path_host: '{{ wordpress_compose_src }}/mariadb/mariadb.conf'
wordpress_db_conf_path_dest: /etc/mariadb.conf
wordpress_db_sql_template_path_host: '{{ wordpress_compose_src }}/mariadb/init.sql'
wordpress_db_sql_template_path_dest: /docker-entrypoint-initdb.d/init.sql
wordpress_db_dir_path_dest: "{{ global_db_dir | default('/var/lib/mysql') }}"
wordpress_db_error_log_path: '{{ wordpress_db_dir_path_dest }}/mariadb.err'
wordpress_db_socket: /run/mysqld/mysqld.sock

# MariaDB
wordpress_db_port: 3306
wordpress_db_innodb_buffer_pool_size: 128M
wordpress_db_user: wp_user
wordpress_db_root_password: "{{ global_db_root_password | default('dev_db_admin_pass_fallback') }}"
wordpress_db_admin_default_password: "{{ global_db_admin_default_password | default('dev_db_admin_pass_fallback') }}"
wordpress_db_password: "{{ global_db_password | default('dev_db_pass_fallback') }}"
wordpress_db_group: mysql
wordpress_db_mem_limit: 512m
wordpress_db_mem_res_limit: 256m
wordpress_db_validate_cmd: ''
wordpress_db_name: wordpress
wordpress_db_container_name: mariadb

# Wordpress
wordpress_wp_uid: '{{ wordpress_apko_uid }}'
wordpress_wp_gid: '{{ wordpress_apko_gid }}'
wordpress_wp_dir_path_dest: "{{ global_wp_dir | default('/var/www/html') }}"
wordpress_wp_admin_user: wp-admin
wordpress_wp_admin_default_password: "{{ global_wp_admin_default_password | default('dev_wp_admin_pass_fallback') }}"
wordpress_wp_admin_email: admin@cloud.one
wordpress_wp_mem_limit: 256m
wordpress_wp_mem_res_limit: 128m
wordpress_wp_container_name: wordpress
wordpress_wp_site_title: '{{ inventory_hostname }}'
wordpress_wp_theme: twentytwentythree
wordpress_wp_url: "{{ global_wp_siteurl | default('http://localhost') }}"

# Angie
wordpress_angie_conf_path_host: '{{ wordpress_compose_src }}/angie/angie.conf'
wordpress_angie_conf_path_dest: /etc/angie/angie.conf
wordpress_angie_wp_root: '{{ wordpress_wp_dir_path_dest }}'
wordpress_angie_container_name: angie
# wordpress_assets_host_path: '{{ wordpress_compose_src }}/wordpress/assets'

# PHP My admin
wordpress_phpmyadmin_blowfish_secret: '{{ global_phpmyadmin_blowfish_secret }}'

# TLS
wordpress_cert_host_dir: '{{ wordpress_compose_src }}/angie/certs'
wordpress_cert_crt_path: "{{ wordpress_cert_host_dir }}/{{ wordpress_domain_name }}.crt"
wordpress_cert_key_path: "{{ wordpress_cert_host_dir }}/{{ wordpress_domain_name }}.key"
wordpress_cert_csr_path: '{{ wordpress_cert_host_dir }}/{{ wordpress_cert_domain }}.csr'
