---

- name: Populate db conf
  ansible.builtin.template:
    src: mariadb.conf.j2
    dest: "{{ __wordpress_db_conf_path_host }}"
    group: admins
    mode: '0644'
    validate: "{{ wordpress_db_validate_cmd | default(omit) }}"

- name: Populate init sql
  ansible.builtin.template:
    src: init.sql.j2
    dest: "{{ __wordpress_db_sql_template_path_host }}"
    group: admins
    mode: '0644'

- name: Populate Angie conf
  ansible.builtin.template:
    src: angie.conf.j2
    dest: "{{ __wordpress_angie_conf_path_host }}"
    group: admins
    mode: '0644'

- name: Set dynamic target directory
  ansible.builtin.set_fact:
    __wordpress_target_dir: "{{ wordpress_compose_src | default(__wordpress_project_path) }}"

- name: Populate docker compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ __wordpress_target_dir }}/docker-compose.yml"
    mode: '0640'
  delegate_to: "{{ wordpress_delegate_host | default(inventory_hostname) }}"
  become: "{{ wordpress_become_compose | default(true) }}"

# delegated to localhost in test
- name: launch docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ __wordpress_target_dir }}"
    state: present
  delegate_to: "{{ wordpress_delegate_host | default(inventory_hostname) }}"
  become: "{{ wordpress_become_compose | default(true) }}"
