---
# - name: Reload angie
#   community.docker.docker_container_exec:
#     container: "{{ wordpress_angie_container_name }}"
#     command: angie -s reload
#   delegate_to: "{{ wordpress_delegate_host | default(inventory_hostname) }}"
#   become: "{{ wordpress_become_compose | default(true) }}"
#   failed_when: false
- name: Reload angie
  community.docker.docker_compose_v2:
    project_src: '{{ wordpress_compose_src }}'
    state: restarted
    services: [angie]
  delegate_to: '{{ wordpress_delegate_host | default(inventory_hostname) }}'
  become: '{{ wordpress_become_compose | default(true) }}'
