events {}

http {
	include /etc/angie/prometheus_all.conf;
	server {
		listen 8080;
		status_zone main_server;

		location / {
			status_zone wordpress;
			proxy_pass http://wordpress:80;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
		}

		location /phpmyadmin/ {
			status_zone phpmyadmin;
			proxy_pass http://phpmyadmin:80/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
		}

		location /status/ {
			api /status/;
		}
		location /metrics/ {
			prometheus all;
		}
	}
}
