---
# wordpress - molecule/default/converge.yml
- name: Converge
  hosts: all
  gather_facts: true
  # those variables remain in converge as they influence role behavior
  vars:
    wordpress_delegate_host: localhost
    wordpress_become_compose: false
  tasks:
    - name: Include wordpress role
      ansible.builtin.include_role:
        name: wordpress
