---
# wordpress - molecule/default/molecule.yml
dependency:
  name: galaxy
  options:
    requirements-file: ../../../requirements.yml
driver:
  name: docker
platforms:
  - name: docker-ubuntu-test
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    pre_build_image: true
    user: root
    volumes:
      - /lib/modules:/lib/modules:ro
      - "${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock"
      - /tmp/${USER}_molecule:/tmp/molecule_shared
provisioner:
  name: ansible
  config_options:
    defaults:
      host_key_checking: false
      remote_tmp: /tmp/.ansible/tmp
      roles_path: ../../../
      stdout_callback: yaml
    ssh_connection:
      pipelining: false
  ansible_args:
    - --diff
    - -vvv
    - --extra-vars
    - >
      wordpress_expose_http=8080
      wordpress_expose_https=8443
      wordpress_compose_src=/tmp/molecule_shared/wordpress_stack
      wordpress_become_compose=false
  env:
    ANSIBLE_ROLES_PATH: ../../../
    ANSIBLE_STDOUT_CALLBACK: default
    ANSIBLE_CALLBACK_RESULT_FORMAT: yaml
  group_vars: ../../../../../group_vars
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - dependency
    - syntax
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
