---
# wordpress - molecule/default/prepare.yml
- name: Prepare instance with bootstrap requirements
  hosts: all
  become: true
  tasks:
    - name: Ensure APT cache is up to date
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker CLI only (required for Ansible community.docker modules)
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Execute bootstrap role to create groups and directories
      ansible.builtin.include_role:
        name: "bootstrap"
