---
# paths on host
__wordpress_db_conf_path: 'etc/my.cnf.d/50-server.cnf'
__wordpress_db_sql_template_path: '/etc/mysql/init.sql.template'
__wordpress_db_socket: '/run/mysqld/mysqld.sock'
__wordpress_db_dir_path: '/var/lib/mysql'
__wordpress_wp_dir_path: '/var/www/wordpress'
__wordpress_db_error_log_path: '/var/lib/mysql/mariadb.err'
__wordpress_angie_conf_path: '/etc/nginx/angie.conf'
__wordpress_angie_ssl_port: 443