name: Ansible Lint

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # python is installed on ubuntu
      # yet it is safer to not use system version
      # so that system packages don't mess with project's
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Linting tools and dependencies
        run: |
          python -m pip install --upgrade pip &&
          pip install yamllint ansible-lint ansible-navigator "ansible-core>=2.15,<2.16"

      - name: Run Yaml Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .

      - name: Run Ansible Lint
        run: |
          touch .ansible.ci.cfg
          if [ -n "community.general" ]; then
            ansible-galaxy collection install community.general
          fi
          if [ -n "community.crypto" ]; then
            ansible-galaxy collection install community.crypto
          fi
          if [ -n "community.docker" ]; then
            ansible-galaxy collection install community.docker
          fi
          ansible-lint ansible/
        env:
          ANSIBLE_CONFIG: ".ansible.ci.cfg"
          ANSIBLE_VAULT_PASSWORD_LIST: "cloudone=${{ secrets.VAULT_PASS_CLOUDONE }}"
